# -*- coding: utf-8 -*-
"""Extracting data from JSON.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHuVoTwDQ1WCWfDmMghWq-DDlMk5VGbx
"""

# Sample data: http://py4e-data.dr-chuck.net/comments_42.json (Sum=2553)
# Actual data: http://py4e-data.dr-chuck.net/comments_851241.json (Sum ends with 1)

import json
import urllib.request
a = 0
 
url = input('Enter - ')
js = urlopen(url).read()
 
pj = json.loads(js)           #stores dicts, python objects, iterate them
x = json.dumps(pj,indent = 2) #json here, remember is just a string, cant access them using x['key']
 
for z in pj['comments']:
  b = z['count']
  a = a+b
print(a)

